
=head1 EXAMPLES

=head2 Example 1. BaseN+1 mode (default), charsets ?d, ?l, ?u, ?s (default)

    $ pathwell-id2topology 2184
    ID='2184'; Topology='?u?l?l?d?s';

=head2 Example 2. Bitmask mode, charsets ?d, ?l, ?u, ?s

    $ pathwell-id2topology -t bitmask 38483
    ID='38483'; Topology='?u?l?l?d?s';

=head2 Example 3. Bitmask mode, charsets ?d, ?l, ?u, ?s, ?f, ?x, STDIN

    echo '1222725' | pathwell-id2topology -t bitmask -s 3 -f -
    ID='1222725'; Topology='?u?f?l?d?x';

