
=head1 EXAMPLES

=head2 Example 1. Create PathWell Database in Current Directory

The command shown below creates a new PathWell test database in the
current directory.

    $ pathwell-create-db -d PathWellTest.db

=head2 Example 2. Create PathWell Database in the Standard System Directory

The command shown below creates a new PathWell test database in
the standard system directory.  The B<-c> option ensures that
intermediate directories are automatically created if missing.

    $ pathwell-create-db -c -d /var/lib/PathWell/PathWellTest.db

=head2 Example 3. Create PathWell Database Using Alternate Blacklist File

The command shown below creates a new PathWell test database in the
current directory with a custom blacklist file called 'test_blacklist'.

    $ pathwell-create-db -f test_blacklist -d PathWellTest.db

