
=head1 EXAMPLES

=head2 Example 1. Password Conversion Using Default Token Set

The command shown below converts the specified password
(i.e., 'Summer2013!') to a corresponding topology (i.e.,
'?u?l?l?l?l?l?d?d?d?d?s').  This conversion is performed using the
default token set (i.e., [dlus]).

    $ pathwell-pw2topology 'Summer2013!'
    Password='Summer2013!'; Topology='?u?l?l?l?l?l?d?d?d?d?s';

=head2 Example 2. Charsets ?d, ?l, ?u, ?s (default), STDIN

    $ echo 'Password123.' | pathwell-pw2topology -f -
    Password='Password123.'; Topology='?u?l?l?l?l?l?l?l?d?d?d?s';

=head2 Example 3. Multiple Password Conversions Using Default Token Set

The command shown below converts a list of passwords, supplied on
stdin, to their corresponding topologies.  The default token set
is used.

    $ for value in 'Summer2013!' 'Password321' 'Slim#Chance' ; do \
    >   echo ${value} | pathwell-pw2topology -f - ; \
    > done
    Password='Summer2013!'; Topology='?u?l?l?l?l?l?d?d?d?d?s';
    Password='Password321'; Topology='?u?l?l?l?l?l?l?l?d?d?d';
    Password='Slim#Chance'; Topology='?u?l?l?l?s?u?l?l?l?l?l';

If the passwords had been listed (one per line) in a file named
'input.list', the same results could be achieved with:

    $ pathwell-pw2topology -f input.list
    Password='Summer2013!'; Topology='?u?l?l?l?l?l?d?d?d?d?s';
    Password='Password321'; Topology='?u?l?l?l?l?l?l?l?d?d?d';
    Password='Slim#Chance'; Topology='?u?l?l?l?s?u?l?l?l?l?l';

