
=head1 OPTIONS

=over 4

=item B<[-f {file|-}]>

Specifies a file containing items, one per line, to be converted.
A value of '-' will cause the program to read from stdin.

=item B<[-s token-set]>

Specifies the ID of the token set to use for performing conversions.
The following token sets are supported:

    1 - [dlus] (default)
    2 - [dlusf]
    3 - [dlusfx]
    4 - [dlusfxH]

=back

